<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Comsemusiserver extends CI_Controller {
public function index()
{
	
}
///userlogin() is the api used to do login 
/**
 * 
 *This function is used to do login it calls the login model 
 *and calls doLogin() method and pass the data sent by the user
 *doLogin function takes email and password as data.
 */
public function userlogin()                          ///userlogin() is the api used to do login 
{
	if(isset($_POST['data']) && isset($_POST['format']) && isset($_POST['datatype']))   /// checks the availability of all the parameters
	{
		
		if($this->input->post('format')=="json" && $this->input->post('datatype')=="log")///checks the correctness of the all the parameters
		{
			$jsonArray=json_decode($_POST['data'],true);                                 ///data is converted json to array
			$this->load->model("login");                                                 ///loads the model login 
			$this->login->doLogin($jsonArray);                                           ///calls doLogin and pass the email id in jsonArray variable
		}
		else 
		/**
		 * this loop will be executed only if there is any mistake with parameters 
		 * 
		 */
		{
			echo 'false';                                                                   
			echo "<br>";
			echo "enter all valid parameters";
			header('HTTP/1.1 400 Bad Request Please provide a values for all the parameters');
		}
	}
	else 
	/**
	 * this loop will be executed only if all the parameters are entered.
	 */
	{
		
		echo 'false';echo "<br>";
		header('HTTP/1.1 400 Bad Request Please provide a valid parameters');
	}
}
/**
 * This functionis used to do registration and calls registration model to do registration 
 * and takes email as data and sends autogenerated password to corresponding Email.
 * 
 */
public function userregistration()
{
	print_r($_POST);
	if(isset($_POST['data']) && isset($_POST['format']) && isset($_POST['datatype']))
	{
		if($this->input->post('format')=="json" && $this->input->post('datatype')=="log")
		{
			$jsonArray=json_decode($_POST['data'],true);
			$this->load->model("registration");
			$this->registration->register($jsonArray);
		}
		else
		{
			echo 'false';echo "<br>";
			header('HTTP/1.1 400 Bad Request Please provide a valid values ');
		}
	}
	else
	{
		echo 'false';echo "<br>";
		header('HTTP/1.1 400 Bad Request Please provide a valid parameters');
	}
	
}
/**
 * 
 * 
 * 
 */
public function addLog()
{
	if(isset($_POST['data']) && isset($_POST['format']) && isset($_POST['datatype']))
	{
		if($this->input->post('format')=="json" && $this->input->post('datatype')=="log")
		{
			$Data=json_decode($_POST['data'],true);
			$TotalData=(int)$_POST['noofdata'];
			for ($i=0;$i<$TotalData;$i++)
			{
				$this->load->model("log");
				$this->log->addrawLog($Data[$i],$_POST['email']);
			}
		}
		else 
		{
			echo 'false';echo "<br>";
			header('HTTP/1.1 400 Bad Request Please provide a valid parameters');
		}
	}
	else
	{
		echo 'false';
		
		header('HTTP/1.1 400 Bad Request Please provide values for all the Parameters'.$_POST);
	}
}
public function addContact()
{
	if($this->dataCheck($_POST))
	{
		if($this->input->post('format')=="json" && $this->input->post('datatype')=="contact")
		{
			$this->load->model('contact');
			$this->contact->addContactDetails($data,$_POST['email']);
		}
		else {
			echo 'false';
		header('HTTP/1.1 400 Bad Request Please provide correct values for all the parameters');
		}
	}
	else {
		echo 'false';
		header('HTTP/1.1 400 Bad Request Please provide values for all the Parameters');
	}
}
public function addGyro()
{
if($this->dataCheck($_POST))
	{
		if($this->input->post('format')=="json" && $this->input->post('datatype')=="gyroscope")
		{
			$this->load->model('gyroscope');
			$this->gyroscope->addData($data);
		}
		else {
			echo 'false';
		header('HTTP/1.1 400 Bad Request Please provide correct values for all the parameters');
		}
	}
	else {
		echo 'false';
		header('HTTP/1.1 400 Bad Request Please provide values for all the Parameters');
	}
}
public function dataCheck($data)
{
	if(isset($_POST['data']) && isset($_POST['format']) && isset($_POST['datatype']))
	return true;
	else 
	return false;
}
}